# Generated by Django 4.1.7 on 2023-03-20 19:36

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to=user_app.models.upload_to),
        ),
    ]
