# Generated by Django 4.1.7 on 2023-03-07 18:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to)),
                ('ISBN', models.IntegerField()),
                ('year', models.IntegerField()),
                ('avg_rating', models.FloatField(default=0)),
                ('number_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
