# Generated by Django 4.1.7 on 2023-04-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='user_rated_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user_rater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbook',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='book_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbook',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='book_rater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='books_owned', through='core.UserBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user_rated_id', 'user_rater_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('book_owner_id', 'book_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book_id', 'book_rater_id')},
        ),
    ]
