# Generated by Django 4.1.7 on 2023-03-23 11:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book_image_url',
            field=models.ImageField(blank=True, default='default_book.png', null=True, upload_to=core.models.upload_to),
        ),
    ]
