# Generated by Django 4.1.7 on 2023-04-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookrating', to='core.book'),
        ),
    ]
